### ISSUE TITLE
Provide a contextual Gauge type

### ISSUE THREAD

**Issue by seh** [Netflix/servo#319]
At present, Servo offers two types of contextual `Monitor`s derived from `AbstractContextualMonitor`: `ContextualCounter` and `ContextualTimer`. Lacking here is a type of contextual `Gauge` (which presumably be called something like `ContextualGauge`).

Would it be possible to add such a type? Did the maintainers consider this idea previously and reject it?

**Comment by brharrington** [comment]
For our use-cases the context is captured when some activity occurs, e.g., when the increment call is made to a counter. Gauges typically aren't updated directly, they are a handle to read a value right now such as the current size of a thread pool or the current temperature. 

What is your use-case?

**Comment by seh** [comment]
My intended use case is tracking the number of active, extant requests to a subsystem in our service. There are different kinds of requests, which I'd like to identify and disambiguate by way of a tag. Like I do with my `ContextualCounter`s, I would bind a particular tag value (such as "_operation_ = _do_something_") higher in the call stack, and allow the "active requests" gauge to track the active count, partitioned by operation kind.

Of course, I can create separate `Gauge` instances for each operation kind, and aggregate them elsewhere, but the same is true for most of my uses of `ContextualCounter`.

**Comment by brharrington** [comment]
Feel free to submit a PR.

The use-case makes sense, but it would have to get used pretty carefully. If a failure occurs and the gauge is not updated or updated too many times when a request completes, then the state of the gauge is bad forever. These sort of failures can be hard to track down because they are often noticed much later when it becomes obvious the reported value is wrong. We try to avoid these issues were possible by querying the authoritative source rather than trying to keep track of it ourselves, e.g., query the thread pool for number of threads vs trying to keep track as tasks are submitted and update on completion. However, it doesn't sound like the subsystem would understand the context in your case.

**Comment by seh** [comment]
> However, it doesn't sound like the subsystem would understand the context in your case.

Right. There isn't an existing "source of truth" that could be polled here that would be different from the gauge itself. That is, we could use a(n atomic) integer that we bump when we're processing a request, and annotate that field with `@Gauge`, but that's not any different from just creating a `LongGauge` field.

**Comment by brharrington** [comment]
Will fix on the linked spectator issue, no plans to add this functionality to servo.
