### ISSUE TITLE
Where are BucketConfig's default buckets defined?

### ISSUE THREAD

**Issue by seh** [Netflix/servo#321]
The documentation for class [`com.netflix.servo.monitor.BucketConfig`](https://github.com/Netflix/servo/blob/b91dae4a0c73eaf75cf91575414d9965de400e3d/servo-core/src/main/java/com/netflix/servo/monitor/BucketConfig.java#L26) promises the following:

> By default we publish count (number of times the timer was executed), totalTime, and the counts and times for the following buckets: 0ms, 100ms, 200ms, 500ms, 1000ms 2000ms, 3000ms, 5000ms

I don't see where these default buckets are defined in the actual code. Are these defaults actually provided, or do I need to define the buckets myself?

**Comment by dmuino** [comment]
Looking at the code you're correct. If you don't provide buckets you'll get a NPE. I'll fix the documentation to make it clear there are no default buckets. Thanks for the report.

**Comment by seh** [comment]
Thank you. Do you have any example code that does set up the buckets like the documentation describes (or described)? I'll consider contributing a `Buckets` factory type if there are several useful recipes (e.g. uniformly sized buckets, exponentially growing buckets).

**Comment by nohros** [comment]
Can you describe how BucketTimer is used internally on Netflix, if it is used at all. I tried to use the BucketTimer but I fail do understand how can I use it like a percentile as described by the docs.

**Comment by brharrington** [comment]
We are typically looking at aggregates that we can slice and dice by the tags. Percentiles don't work well in this mode because we can only support simple aggregates (sum, count, min, max). So you wind up getting locally computed percentiles that are then averaged to get a summary for some grouping such as cluster. To get an accurate percentile you really need to keep all the samples which isn't feasible for our operational monitoring where we have tight SLAs on when data should be actionable and need it to be cheap and fast to query.

We are experimenting with some approaches for maintaining percentile data while still being able to slice and dice with a reasonable overhead. However, it is still has more overhead than simple bucket counters. So it would likely get used sparingly for cases where the bucket approach doesn't work.

The bucketing approach is a simple way to handle some of the same use-cases as percentiles, but that works well with simple aggregates. Specifically we use them to:

* Get an idea of the distribution when we know the primary range of values.
* Track whether the distribution is within an SLA.

To give an example, we have a data pipeline that publishes data regularly and there is a bucket timer on the request. The simplest view is just looking at the count grouped by the buckets:

![rps](https://cloud.githubusercontent.com/assets/1289028/7579405/63db0466-f818-11e4-8dd5-08a1cc7a6b6d.png)

This graph is showing the overall number of requests and at the same time lets me see the latency distribution for the requests. The buckets in this case are showing the number of requests with a latency less than the bucket name. We make sure the bucket labels are lexically sortable so they are easy to order in a group by and a less than equal query operator can be used to group lower buckets.

We can also view that as a percentage graph:

![percent](https://cloud.githubusercontent.com/assets/1289028/7579454/1b5f6c4e-f819-11e4-9738-a2c45e49fada.png)

The bucket approach doesn't let me know what a specific percentile is, e.g., I can't answer what is the 99th percentile for a given time. However, I can tell for a given time the percentile that is at the bucket boundaries. For tracking an SLA if you know the 99th percentile should be less than 4s, then you just need to ensure that the SLA value is one of the bucket boundaries. Then you can see how often you are within SLA with something like:

![sla](https://cloud.githubusercontent.com/assets/1289028/7579509/dee501d8-f819-11e4-9b9b-73462884a9e7.png)

That is basically just the base query ANDed with a condition `bucket <= 4s`.

The main downside to buckets:

* They aren't adaptive. To get the simple aggregation you need global agreement on the set of buckets so they need to be planned out.
* Not as common so it isn't how most people are used to thinking about the problem.

**Comment by nohros** [comment]
Thanks for your very descriptive explanation, the concepts is much more clear now.

**Comment by seh** [comment]
I didn't see a commit that reworded the documentation. While the truth is on record here, the documentation still may mislead other users of the library.
