### ISSUE TITLE
AwsInjectableTag: AUTOSCALE_GROUP does not work outside us-east-1

### ISSUE THREAD

**Issue by rattigan** [Netflix/servo#348]
The implementation of getAutoScaleGroup never sets a region on the AutoScaling client, which defaults to us-east-1. If the monitored instance is not in us-east-1, the describe-autoscaling-instances request fails to return anything, and the tag will have the value 'undefined'.

**Comment by rattigan** [comment]
Looking at the AwsServiceClients class, there is a way to inject a region-specific endpoint with a system property. However, it would be nicer if the region was culled from the instance metadata to guarantee that the appropriate endpoint was used, rather than relying on external configuration.

**Comment by brharrington** [comment]
I'll take a look when I get a chance, otherwise PRs welcome.

For some context, we don't use the AwsInjectableTag class internally. The auto-scaling group and other general tagging information we rely on is setup in userdata so it is easily accessible on the instance. Unfortunately we cannot get the ASG name from the metadata service directly. Then the observer that sends the data in adds the common tags to all metrics when reported.

**Comment by brharrington** [comment]
PRs welcome, since there is not an internal use-case we do not plan to fix this.
