### ISSUE TITLE
Make findbugs dependency as "provided"

### ISSUE THREAD

**Issue by ivelichko** [Netflix/servo#356]
At the moment, servo-core has com.google.code.findbugs:annotations in "compile" scope. Taking into account that  these annotations are used only during code analysis and have no influence on functionality, it would be nice not to have findbugs library as a transitive dependency. So please change its scope to provided, if it's possible to do in gradle.

**Comment by brharrington** [comment]
I agree it is not ideal to have stuff like that in the final published library. If I recall correctly, the reason it is compile is because some tools break when there are references to annotations that are not in the classpath, e.g.:

https://issues.scala-lang.org/browse/SI-7751

Provided scope is not transitive so it would mean each consumer would need to add it. Maybe we should just cleanup the uses and remove the dependency all together.

**Comment by ivelichko** [comment]
@brharrington  thanks for the explanation. If it's not possible to get rid of all that annotations, findbugs still can be configured by XML (yes, it's ugly, but at least it doesn't propagate dependencies). Btw there is already findbugs 3.0
