### ISSUE TITLE
Min/max metric values are zero even though totalTime and count are non-zero

### ISSUE THREAD

**Issue by hiteshdholaria** [Netflix/servo#389]
We have been facing an issue in which we are not getting the correct values for min/max gauge values. Even though, totalTime and count metrics are non-zero, we get zero values for min/max metrics. This behavior is arbitrary and not regular, hence some of the times it gives the correct values for min/max, but for most of the times, it gives zero values.

We are using a custom BasicTimer (e.g., DenormalizedBasicTimer which extends AbstractMonitor<Long> and implements Timer, CompositeMonitor<Long>) and have registered MonitorRegistryMetricPoller as a poller polling every 30 seconds.

Java: 1.7.0_02
Netflix Servo: 0.9.2
OS: Windows Server 2008 (64-bit)

**Comment by brharrington** [comment]
That isn't a lot to go on. Can you provide sample code for the timer implementation?

**Comment by hiteshdholaria** [comment]
@brharrington Please find the below sample code for the timer.

package com.myapp.servo;

import java.util.List;
import java.util.concurrent.TimeUnit;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.MoreObjects;
import com.netflix.servo.monitor.AbstractMonitor;
import com.netflix.servo.monitor.CompositeMonitor;
import com.netflix.servo.monitor.MaxGauge;
import com.netflix.servo.monitor.MinGauge;
import com.netflix.servo.monitor.Monitor;
import com.netflix.servo.monitor.MonitorConfig;
import com.netflix.servo.monitor.NumericMonitor;
import com.netflix.servo.monitor.Stopwatch;
import com.netflix.servo.monitor.TimedStopwatch;
import com.netflix.servo.monitor.Timer;
import com.netflix.servo.publish.MonitorRegistryMetricPoller;
import com.netflix.servo.tag.Tag;
import com.netflix.servo.tag.Tags;
import com.netflix.servo.util.Clock;
import com.netflix.servo.util.ClockWithOffset;
import com.netflix.servo.util.UnmodifiableList;

/**
 * A simple timer implementation providing the total time, count, min, and max for the times that
 * have been recorded.<br>
 * This is different from {@link com.netflix.servo.monitor.BasicTimer} as it provides recorded
 * values of totalTime and count instead of providing normalized values
 */
public class DenormalizedBasicTimer extends AbstractMonitor<Long> implements Timer, CompositeMonitor<Long> {

  private static final Logger LOGGER = LoggerFactory.getLogger(DenormalizedBasicTimer.class);

	private static final String STATISTIC = "statistic";
  private static final String UNIT = "unit";

  private static final Tag STAT_TOTAL = Tags.newTag(STATISTIC, "totalTime");
  private static final Tag STAT_COUNT = Tags.newTag(STATISTIC, "count");
  private static final Tag STAT_MIN = Tags.newTag(STATISTIC, "min");
  private static final Tag STAT_MAX = Tags.newTag(STATISTIC, "max");

  private final TimeUnit timeUnit;
  private final double timeUnitNanosFactor;
  private final DeltaCounter totalTime;
  private final DeltaCounter count;
  private final MinGauge min;
  private final MaxGauge max;

  private final List<Monitor<?>> monitors;

  private static final class FactorMonitor<T extends Number> extends AbstractMonitor<Double> implements NumericMonitor<Double> {
    private final Monitor<T> wrapped;
    private final double factor;

    private FactorMonitor(Monitor<T> wrapped, double factor) {
      super(wrapped.getConfig());
      this.wrapped = wrapped;
      this.factor = factor;
    }

    @Override
    public Double getValue(int pollerIndex) {
      return wrapped.getValue(pollerIndex).doubleValue() * factor;
    }
  }

  /**
   * Creates a new instance of the timer with a unit of milliseconds.
   */
  public DenormalizedBasicTimer(MonitorConfig config) {
    this(config, TimeUnit.MILLISECONDS);
  }

  /**
   * Creates a new instance of the timer.
   */
  DenormalizedBasicTimer(MonitorConfig config, TimeUnit unit, Clock clock) {
    super(config);

    final Tag unitTag = Tags.newTag(UNIT, unit.name());
    final MonitorConfig unitConfig = config.withAdditionalTag(unitTag);
    timeUnit = unit;
    timeUnitNanosFactor = 1.0 / timeUnit.toNanos(1);

    totalTime = new DeltaCounter(unitConfig.withAdditionalTag(STAT_TOTAL));
    count = new DeltaCounter(unitConfig.withAdditionalTag(STAT_COUNT));
    min = new MinGauge(unitConfig.withAdditionalTag(STAT_MIN));
    max = new MaxGauge(unitConfig.withAdditionalTag(STAT_MAX));

    final FactorMonitor<Number> totalTimeFactor =
        new FactorMonitor<Number>(totalTime, timeUnitNanosFactor);
    final FactorMonitor<Long> minFactor = new FactorMonitor<Long>(min, timeUnitNanosFactor);
    final FactorMonitor<Long> maxFactor = new FactorMonitor<Long>(max, timeUnitNanosFactor);

    monitors = UnmodifiableList.<Monitor<?>>of(totalTimeFactor, count, minFactor, maxFactor);
    
    LOGGER.warn("DenormalizedBasicTimer: monitors = {}, monitors.size = {}", monitors, monitors.size());
  }

  /**
   * Creates a new instance of the timer.
   */
  public DenormalizedBasicTimer(MonitorConfig config, TimeUnit unit) {
    this(config, unit, ClockWithOffset.INSTANCE);
  }


  /**
   * {@inheritDoc}
   */
  @Override
  public List<Monitor<?>> getMonitors() {
    return monitors;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Stopwatch start() {
    Stopwatch s = new TimedStopwatch(this);
    s.start();
    return s;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public TimeUnit getTimeUnit() {
    return timeUnit;
  }

  private void recordNanos(long nanos) {
    if (nanos >= 0) {
      totalTime.increment(nanos);
      count.increment();
      min.update(nanos);
      max.update(nanos);
    }
  }

  /**
   * {@inheritDoc}
   */
  @Override
  @Deprecated
  public void record(long duration) {
    long nanos = timeUnit.toNanos(duration);
    recordNanos(nanos);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public void record(long duration, TimeUnit unit) {
    recordNanos(unit.toNanos(duration));
  }

  private double getTotal(int pollerIndex) {
    return totalTime.getValue(pollerIndex).doubleValue() * timeUnitNanosFactor;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long getValue(int pollerIndex) {
    final long cnt = count.getValue(pollerIndex).longValue();
    final long value = (long) (getTotal(pollerIndex) / cnt);
    return (cnt == 0) ? 0L : value;
  }

  /**
   * Get the total time for all updates.
   */
  public Double getTotalTime() {
    return getTotal(0);
  }

  /**
   * Get the total number of updates.
   */
  public Long getCount() {
    return count.getValue(0).longValue();
  }

  /**
   * Get the min value since the last reset.
   */
  public Double getMin() {
    return min.getCurrentValue(0) * timeUnitNanosFactor;
  }

  /**
   * Get the max value since the last reset.
   */
  public Double getMax() {
    return max.getCurrentValue(0) * timeUnitNanosFactor;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null || !(obj instanceof DenormalizedBasicTimer)) {
      return false;
    }
    DenormalizedBasicTimer m = (DenormalizedBasicTimer) obj;
    return config.equals(m.getConfig()) && totalTime.equals(m.totalTime) && count.equals(m.count) &&
        min.equals(m.min) && max.equals(m.max);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public int hashCode() {
    int result = config.hashCode();
    result = 31 * result + totalTime.hashCode();
    result = 31 * result + count.hashCode();
    result = 31 * result + min.hashCode();
    result = 31 * result + max.hashCode();
    return result;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String toString() {
    return MoreObjects.toStringHelper(this)
      .add("config", config)
      .add("totalTime", totalTime)
      .add("count", count)
      .add("min", min)
      .add("max", max)
      .toString();
  }
}

**Comment by dmuino** [comment]
That doesn't give us much. It's basically the same as a BasicTimer but instead of using a `StepCounter` for totalTime and count it's using a `DeltaCounter` (which is something you'd have created - note that a `BasicCounter` is just a wrapper around an `AtomicLong` in case you needed that style of counter).

`MinGauge` and `MaxGauge` use `StepLong` to implement the functionality needed. That requires you to properly set the system property `servo.pollers`. By default `servo.pollers` is 60000,10000 which prepares you to have two pollers one polling every 60s and one polling every 10s. If you only have one poller and that poller runs every 30s then you should set it to `-Dservo.pollers=30000`

Note that `StepLong` would report the value for the previously completed polling interval, so if your `DeltaCounter` is reporting the current value there will be a mismatch. It works fine in `BasicTimer` because `StepCounter` and the min and max gauges use `StepLong` so the reported values are consistent.

**Comment by hiteshdholaria** [comment]
@brharrington, @dmuino If we use BasicCounter instead of our own DeltaCounter, it gives the complete list of metrics (as expected), however those metrics seems to be coming in different scales, see the below example metrics produced when BasicCounter was used.

(totalTime=75.3420035666667, count=0.0166666666666667, min=4520.520214, max=4520.520214)

Count should have been 1 rather than 1/60. Moreover, other metrics seems to be normalized differently!

**Comment by brharrington** [comment]
For the original question about 0 values for min/max, I think @dmuino is correct that the most likely candidate is the `servo.pollers` setting. If you set a system property with `-Dservo.pollers=30000` do you still see problems?

> If we use BasicCounter instead of our own DeltaCounter, it gives the complete list of metrics (as expected), however those metrics seems to be coming in different scales

In both cases the value for the counter is a rate, the difference is just what time period is used for the denominator. The default always reports as a rate per second. In your DeltaCounter it would be a rate per reporting interval. We prefer a rate per second because it is easier to compare samples collected with different intervals and is the more common value users think about for common counters. For example, a user wants to know the requests/second hitting their service over time.

> Count should have been 1 rather than 1/60. Moreover, other metrics seems to be normalized differently!

The counters are rates where as the min/max values are sampled values. So for your example (assuming unit of milliseconds which is default for servo):

* `totalTime` -- 75.3420035666667 milliseconds/second
* `count` -- 0.0166666666666667 events/second
* `min` -- 4520.520214 milliseconds
* `max` -- 4520.520214 milliseconds
* `avg` -- `totalTime` / `count` = 4520.520214 milliseconds/event. We don't report a local average because it leads to average of averages problem. Rather we compute the average for presentation using `totalTime/count`. This would have a unit of `(milliseconds/second) / (events/second) = milliseconds/event`.

**Comment by hiteshdholaria** [comment]
@brharrington, @dmuino 
Yes, it still had problems even after setting a system property with -Dservo.pollers=30000.

Well, it makes sense to store rates in the counters! We will scale those counters on our end.

Thanks a lot for the help.

**Comment by brharrington** [comment]
If you update to the latest release does it still show the problem? The description kind of sounds like a bug that was fixed in [0.7.2](https://github.com/Netflix/servo/releases/tag/0.7.2), but if your on 0.9.2 that shouldn't be the case.

**Comment by hiteshdholaria** [comment]
We have tested this with v0.9.2, we cannot go beyond v0.9.2 since we do not use Java 8.
