### ISSUE TITLE
Annotations documentation out of date

### ISSUE THREAD

**Issue by dogonthehorizon** [Netflix/servo#399]
It appears `@Monitor` annotations have not supported the `tags` field since [0.4.35](https://github.com/Netflix/servo/commit/76f1c5d1f5e2dc756bac07e0af5056ead7b7d97d#diff-2497b7d38a093a912d12fa9d15301184). I've updated the documentation to reflect this change, however I don't see how to create a pull request against the wiki through GitHub. Here's a link to the patch for the documentation:
https://gist.github.com/dogonthehorizon/88d9a0c14f8f680afe55ebecd764daea

Let me know if I can provide any further information!

**Comment by brharrington** [comment]
Thanks for the diff. I applied the change:

https://github.com/Netflix/servo/wiki/Annotations/_compare/847888fa03d98eccf40f1aa321651d7fcab601a3...4214abcad98a2ca022e84a1f3b7f690f91975445

As far as I know there isn't a way to support PRs for github wikis and we had to disable public write access due to spam.
